### ISSUE TITLE
Run inference on Test videos without Annotation

### ISSUE THREAD

**Issue by tarushreeg** [wanghao9610/TMANet#32]
Hi,

Thanks for sharing the code. Do you perhaps have the Test script to run the model on a video or a set of consecutive frames, without the ground-truth annotations?
Since we need to call 'mmseg.apis' and provide the cfg file to run the model, I was wondering if you already have the code to do that?

Thanks!

**Comment by wanghao9610** [comment]
Thanks for your attention to my work. I haven't developed the inference demo in the project, you may refer to the image_demo in mmsegmentation(https://github.com/open-mmlab/mmsegmentation/blob/v0.7.0/demo/image_demo.py) for help. It is easy to extend the image_demo to video_demo (pass multi-frame to the model instead of a single image).

**Comment by tarushreeg** [comment]
Great, I'll refer to this link.
Do you also have any results on videos, since the approach aims to improve the temporal relations between frames for video segmentation task? I didn't find any in this repository, so wondering if I missed it.
Thanks!

**Comment by wanghao9610** [comment]
TMANet is a method based on the temporal attention mechanism, which captures the temporal relationship between frames by the attention to the features of multiple frames. You may get some help from the tma_head (TMANet/mmseg/models/decode_heads/tma_head.py).
